name: 'Sbt Dependency Submission'
description: 'Submits the dependency graph of an sbt build to the Github Submission API'
author: 'The Scala Center'
branding:
  icon: 'package'
  color: '#1a84ac'
inputs:
  working-directory:
    description: "The relative path of the working directory of the sbt build."
    required: false
    default: ''
  modules-ignore:
    description: |
      A list of space-separated names of modules to ignore. The action will not resolve nor submit the dependencies of these modules.
      The name of a module contains the name of the project and its binary version.
      Example: `foo_2.13 bar_2.13`
    required: false
    default: ''
  configs-ignore:
    description: |
      A list of space-separated names of configurations to ignore. The action will not submit the dependencies of these configurations.
      Example: `test scala-doc-tool`
    required: false
    default: ''
  on-resolve-failure:
    description: |
      Either 'error' or 'warning'.
      When a dependency resolution failure happens, if 'error' the job will fail and will not submit the snapshot.
      If 'warning', the job will ignore the failing modules and submit the snapshot.
    required: false
    default: error
  additional-sbt-parameters:
    description: |
     Add additional parameters to pass to the sbt command.
     Can be used for example for repository settings, or parameters needed for your repository.
    required: false
    default: ''
  token:
    description: GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner.
    required: false
    default: ${{ github.token }}
  sbt-plugin-version:
    description: Version of the sbt plugin to use.
    required: false
    default: '2.1.2'
runs:
  using: 'node16'
  main: 'dist/index.js'
